[[tests]]
name = "b0"
input =  ["./project04", "-h", "b0.hex", "$project_tests/b0.s"]
expected = """
v2.0 raw
e0810002
ea000000
e0821000
e0823001
e12fff1e
"""
output ="b0.hex"
rubric = 2

[[tests]]
name = "b1"
input =  ["./project04", "-h", "b1.hex", "$project_tests/b1.s"]
expected = """
v2.0 raw
e0810002
eaffffff
e0823001
e12fff1e
"""
output = "b1.hex"
rubric = 2

[[tests]]
name = "cmpi"
input =  ["./project04", "-h", "cmpi.hex", "$project_tests/cmpi.s"]
expected = """
v2.0 raw
e3510007
e12fff1e
"""
output = "cmpi.hex"
rubric = 2

[[tests]]
name = "cmp"
input =  ["./project04", "-h", "cmp.hex", "$project_tests/cmp.s"]
expected =  """
v2.0 raw
e1520003
e12fff1e
"""
output = "cmp.hex"
rubric = 2

[[tests]]
name = "dp2i"
input =  ["./project04", "-h", "dp2i.hex", "$project_tests/dp2i.s"]
expected = """
v2.0 raw
e3a0002a
e12fff1e
"""
output = "dp2i.hex"
rubric = 2

[[tests]]
name = "dp2"
input =  ["./project04", "-h", "dp2.hex", "$project_tests/dp2.s"]
expected = """
v2.0 raw
e1a00001
e12fff1e
"""
output = "dp2.hex"
rubric = 2

[[tests]]
name = "dp3i"
input =  ["./project04", "-h", "dp3i.hex", "$project_tests/dp3i.s"]
expected = """
v2.0 raw
e2821063
e12fff1e
"""
output = "dp3i.hex"
rubric = 2

[[tests]]
name = "dp3"
input =  ["./project04", "-h", "dp3.hex", "$project_tests/dp3.s"]
expected = """
v2.0 raw
e0421003
e12fff1e
"""
output = "dp3.hex"
rubric = 2

[[tests]]
name = "lsi"
input =  ["./project04", "-h", "lsi.hex", "$project_tests/lsi.s"]
expected = """
v2.0 raw
e1a02103
e12fff1e
"""
output = "lsi.hex"
rubric = 2

[[tests]]
name = "memi"
input =  ["./project04", "-h", "memi.hex", "$project_tests/memi.s"]
expected = """
v2.0 raw
e5932000
e58d2004
e12fff1e
"""
output = "memi.hex"
rubric = 2

[[tests]]
name = "quadratic"
input =  ["./project04", "-h", "quadratic.hex", "$project_tests/quadratic_s.s"]
expected = """
v2.0 raw
e00c0090
e0010c91
e0020290
e0810002
e0800003
e12fff1e
"""
output = "quadratic.hex"
rubric = 10

[[tests]]
name = "reverse"
input =  ["./project04", "-h", "reverse.hex", "$project_tests/reverse_s.s"]
expected = """
v2.0 raw
e1a01000
e5d12000
e3520000
0a000001
e2811001
eafffffa
e2411001
e1500001
aa000006
e5d02000
e5d13000
e5c12000
e5c03000
e2800001
e2411001
eafffff6
e12fff1e
"""
output = "reverse.hex"
rubric = 10
