[project]
build = "none"
strip_output = """
Use default settings!
"""

[[tests]]
name = "quadratic"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/quadratic.dig"]
expected = """
quadratic: passed
"""
rubric = 10

[[tests]]
name = "reverse"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/reverse.dig"]
expected = """
reverse: passed
"""
rubric = 10
