[[tests]]
name = "01"
input = ["./lab03", "add4", "1", "1", "1", "1"]
expected = """
add4_c(1, 1, 1, 1) = 4
add4_s(1, 1, 1, 1) = 4
"""
rubric = 10

[[tests]]
name = "02"
input = ["./lab03", "add4", "1", "2", "3", "4"]
expected = """
add4_c(1, 2, 3, 4) = 10
add4_s(1, 2, 3, 4) = 10
"""
rubric = 10

[[tests]]
name = "03"
input = ["./lab03", "add4", "10", "-10", "99", "-99"]
expected = """
add4_c(10, -10, 99, -99) = 0
add4_s(10, -10, 99, -99) = 0
"""
rubric = 10

[[tests]]
name = "04"
input = ["./lab03", "quadratic", "1", "1", "1", "1"]
expected = """
quadratic_c(1, 1, 1, 1) = 3
quadratic_s(1, 1, 1, 1) = 3
"""
rubric = 10

[[tests]]
name = "05"
input = ["./lab03", "quadratic", "2", "2", "3", "4"]
expected = """
quadratic_c(2, 2, 3, 4) = 18
quadratic_s(2, 2, 3, 4) = 18
"""
rubric = 10

[[tests]]
name = "06"
input = ["./lab03", "quadratic", "-3", "-2", "3", "4"]
expected = """
quadratic_c(-3, -2, 3, 4) = -23
quadratic_s(-3, -2, 3, 4) = -23
"""
rubric = 10

[[tests]]
name = "07"
input = ["./lab03", "min", "1", "2"]
expected = """
min_c(1, 2) = 1
min_s(1, 2) = 1
"""
rubric = 10

[[tests]]
name = "08"
input = ["./lab03", "min", "2", "1"]
expected = """
min_c(2, 1) = 1
min_s(2, 1) = 1
"""
rubric = 10

[[tests]]
name = "09"
input = ["./lab03", "min", "-9", "-10"]
expected = """
min_c(-9, -10) = -10
min_s(-9, -10) = -10
"""
rubric = 10

[[tests]]
name = "10"
input = ["./lab03", "min", "99", "99"]
expected = """
min_c(99, 99) = 99
min_s(99, 99) = 99
"""
rubric = 10
