[project]
build = "none"

[[tests]]
name = "quadratic"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/quadratic.dig"]
expected = """
Use default settings!
quadratic: passed
"""
rubric = 10

[[tests]]
name = "factorial"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/factorial.dig"]
expected = """
Use default settings!
factorial: passed
"""
rubric = 10

[[tests]]
name = "sum-array"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/sum-array.dig"]
expected = """
Use default settings!
sum-array: passed
"""
rubric = 10

[[tests]]
name = "search"
input = ["java", "-cp", "$digital", "CLI", "test", "$project.dig", "-tests", "$project_tests/search.dig"]
expected = """
Use default settings!
search: passed
"""
rubric = 20
