[[tests]]
name = "01"
input = ["./project03", "substr", "aaxxyy", "aa"]
expected = """
substr_c(aaxxyy, aa) = 1 0
substr_s(aaxxyy, aa) = 1 0
"""
rubric = 5

[[tests]]
name = "02"
input = ["./project03", "substr", "xxaayy", "aa"]
expected = """
substr_c(xxaayy, aa) = 1 2
substr_s(xxaayy, aa) = 1 2
"""
rubric = 5

[[tests]]
name = "03"
input = ["./project03", "substr", "xxyyaa", "aa"]
expected = """
substr_c(xxyyaa, aa) = 1 4
substr_s(xxyyaa, aa) = 1 4
"""
rubric = 5

[[tests]]
name = "04"
input = ["./project03", "substr", "xxyyaa", "aa"]
expected = """
substr_c(xxyyaa, aa) = 1 4
substr_s(xxyyaa, aa) = 1 4
"""
rubric = 5

[[tests]]
name = "05"
input = ["./project03", "substr", "xxyyaa", "bb"]
expected = """
substr_c(xxyyaa, bb) = 0 0
substr_s(xxyyaa, bb) = 0 0
"""
rubric = 5

[[tests]]
name = "06"
input = ["./project03", "matches", "aaaa", "aa"]
expected = """
matches_c(aaaa, aa) = 3
matches_s(aaaa, aa) = 3
"""
rubric = 5

[[tests]]
name = "07"
input = ["./project03", "matches", "xxaaxxaaxxaaxx", "aa"]
expected = """
matches_c(xxaaxxaaxxaaxx, aa) = 3
matches_s(xxaaxxaaxxaaxx, aa) = 3
"""
rubric = 5

[[tests]]
name = "08"
input = ["./project03", "matches", "xxaaaaxxaaaaxxaaaaxx", "aa"]
expected = """
matches_c(xxaaaaxxaaaaxxaaaaxx, aa) = 9
matches_s(xxaaaaxxaaaaxxaaaaxx, aa) = 9
"""
rubric = 5

[[tests]]
name = "09"
input = ["./project03", "matches", "foobarfobarfobarfoo", "foo"]
expected = """
matches_c(foobarfobarfobarfoo, foo) = 2
matches_s(foobarfobarfobarfoo, foo) = 2
"""
rubric = 5

[[tests]]
name = "10"
input = ["./project03", "matches", "foobarfobarfobarfoo", "baa"]
expected = """
matches_c(foobarfobarfobarfoo, baa) = 0
matches_s(foobarfobarfobarfoo, baa) = 0
"""
rubric = 5

[[tests]]
name = "11"
input = ["./project03", "merge", "1", "1"]
expected = """
merge_c([1], 0, 1, aux[]) = [1]
merge_s([1], 0, 1, aux[]) = [1]
"""
rubric = 5

[[tests]]
name = "12"
input = ["./project03", "merge", "2", "1", "1"]
expected = """
merge_c([1,1], 0, 2, aux[]) = [1,1]
merge_s([1,1], 0, 2, aux[]) = [1,1]
"""
rubric = 5

[[tests]]
name = "13"
input = ["./project03", "merge", "4", "2", "4", "1", "3"]
expected = """
merge_c([2,4,1,3], 0, 4, aux[]) = [1,2,3,4]
merge_s([2,4,1,3], 0, 4, aux[]) = [1,2,3,4]
"""
rubric = 5

[[tests]]
name = "14"
input = ["./project03", "merge", "8", "2", "4", "8", "10", "1", "3", "7", "9"]
expected = """
merge_c([2,4,8,10,1,3,7,9], 0, 8, aux[]) = [1,2,3,4,7,8,9,10]
merge_s([2,4,8,10,1,3,7,9], 0, 8, aux[]) = [1,2,3,4,7,8,9,10]
"""
rubric = 5

[[tests]]
name = "15"
input = ["./project03", "merge", "10", "2", "4", "8", "10", "11", "1", "3", "7", "9", "99"]
expected = """
merge_c([2,4,8,10,11,1,3,7,9,99], 0, 10, aux[]) = [1,2,3,4,7,8,9,10,11,99]
merge_s([2,4,8,10,11,1,3,7,9,99], 0, 10, aux[]) = [1,2,3,4,7,8,9,10,11,99]
"""
rubric = 5

[[tests]]
name = "16"
input = ["./project03", "merge_sort", "1", "1"]
expected = """
merge_sort_c([1], 0, 1, aux[]) = [1]
merge_sort_s([1], 0, 1, aux[]) = [1]
"""
rubric = 5

[[tests]]
name = "17"
input = ["./project03", "merge_sort", "2", "2", "1"]
expected = """
merge_sort_c([2,1], 0, 2, aux[]) = [1,2]
merge_sort_s([2,1], 0, 2, aux[]) = [1,2]
"""
rubric = 5

[[tests]]
name = "18"
input = ["./project03", "merge_sort", "4", "4", "3", "1", "2"]
expected = """
merge_sort_c([4,3,1,2], 0, 4, aux[]) = [1,2,3,4]
merge_sort_s([4,3,1,2], 0, 4, aux[]) = [1,2,3,4]
"""
rubric = 5

[[tests]]
name = "19"
input = ["./project03", "merge_sort", "8", "1000", "10", "100", "1", "2000", "2", "20", "2"]
expected = """
merge_sort_c([1000,10,100,1,2000,2,20,2], 0, 8, aux[]) = [1,2,2,10,20,100,1000,2000]
merge_sort_s([1000,10,100,1,2000,2,20,2], 0, 8, aux[]) = [1,2,2,10,20,100,1000,2000]
"""
rubric = 5

[[tests]]
name = "20"
input = ["./project03", "merge_sort", "21", "100", "80", "90", "70", "60", "50", "40", "30", "20", "10", "10", "8", "9", "7", "6", "5", "4", "3", "2", "1", "0"]
expected = """
merge_sort_c([100,80,90,70,60,50,40,30,20,10,10,8,9,7,6,5,4,3,2,1,0], 0, 21, aux[]) = [0,1,2,3,4,5,6,7,8,9,10,10,20,30,40,50,60,70,80,90,100]
merge_sort_s([100,80,90,70,60,50,40,30,20,10,10,8,9,7,6,5,4,3,2,1,0], 0, 21, aux[]) = [0,1,2,3,4,5,6,7,8,9,10,10,20,30,40,50,60,70,80,90,100]
"""
rubric = 5

