[[tests]]
name = "01"
input = ["./$project", "max3", "1", "3", "2"]
expected = """
max3_c(1, 3, 2) = 3
max3_s(1, 3, 2) = 3
max3_e(1, 3, 2) = 3
"""
rubric = 10

[[tests]]
name = "02"
input = ["./$project", "max3", "-1", "-10", "-20"]
expected = """
max3_c(-1, -10, -20) = -1
max3_s(-1, -10, -20) = -1
max3_e(-1, -10, -20) = -1
"""
rubric = 10

[[tests]]
name = "03"
input = ["./$project", "find_max", "5", "1", "2", "5", "3", "4"]
expected = """
find_max_c([1,2,5,3,4], 5) = 5
find_max_s([1,2,5,3,4], 5) = 5
find_max_e([1,2,5,3,4], 5) = 5
"""
rubric = 10

[[tests]]
name = "04"
input = ["./$project", "find_max", "10", "-1", "99", "1", "2", "3", "4", "5", "6", "7", "0"]
expected = """
find_max_c([-1,99,1,2,3,4,5,6,7,0], 10) = 99
find_max_s([-1,99,1,2,3,4,5,6,7,0], 10) = 99
find_max_e([-1,99,1,2,3,4,5,6,7,0], 10) = 99
"""
rubric = 10

[[tests]]
name = "05"
input = ["./$project", "fib_rec", "5"]
expected = """
fib_rec_c(5) = 5
fib_rec_s(5) = 5
fib_rec_e(5) = 5
"""
rubric = 10

[[tests]]
name = "06"
input = ["./$project", "fib_rec", "10"]
expected = """
fib_rec_c(10) = 55
fib_rec_s(10) = 55
fib_rec_e(10) = 55
"""
rubric = 10

[[tests]]
name = "07"
input = ["./$project", "fib_rec", "19"]
expected = """
fib_rec_c(19) = 4181
fib_rec_s(19) = 4181
fib_rec_e(19) = 4181
"""
rubric = 10

